env:
  browser: false
  commonjs: true
  es6: true
  node: true
  worker: true
  mongo: true
plugins:
  - security
extends:
  - 'eslint:recommended'
  - standard
globals:
  xrequire: readonly
  __basedir: readonly
  oldLog: readonly
  print: readonly
  PrintHistory: readonly
  VulcanDefaults: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-case-declarations: off
  no-console: off
  no-useless-escape: off
  no-inline-comments: off
  no-multi-spaces: off
  standard/object-curly-even-spacing: off
  semi:
    - 2
    - always
  indent: off
