env:
  browser: false
  commonjs: true
  es6: true
  node: true
  worker: true
  mongo: true
plugins:
  - security
extends:
  - 'mudamuda/node' # superior rule set
globals:
  xrequire: readonly
  __basedir: readonly
  oldLog: readonly
  print: readonly
  PrintHistory: readonly
