env:
  browser: false
  commonjs: true
  es6: true
  node: true
  worker: true
  mongo: true
plugins:
  - security
extends:
  - 'eslint:recommended'
  - standard
globals:
  xrequire: readonly
  __basedir: readonly
  oldLog: readonly
  print: readonly
  PrintHistory: readonly
  ParsingTypes: readonly
  VulcanDefaults: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-case-declarations: 0
  no-console: 0
  no-eval: 0
  no-useless-escape: 0
  no-inline-comments: 0
  no-multi-spaces: 0
  semi:
    - 2
    - always
  indent: 0
  curly: 0
