env:
  browser: false
  commonjs: true
  es6: true
plugins:
  - 'security'
extends: 
  - 'eslint:recommended'
  - 'standard'
  - 'plugin:security/recommended'
globals:
  xrequire: readonly
  oldLog: readonly
  printHistory: readonly
  print: readonly
  __basedir: readonly
  ParsingTypes: readonly
  Defaults: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-case-declarations: 'off'
  no-console: 'off'
  no-useless-escape: 'off'
  no-inline-comments: 'off'
  indent: 'off'
  semi: 'off'
  no-multi-spaces: 'off'
  curly: 'off'
  no-eval: 'off'
