env:
  browser: false
  commonjs: true
  es6: true
extends: 'standard'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: 
  no-console: 'off'
  no-undef: 'off'
  no-useless-escape: 'off'
  no-inline-comments: 'off'
  indent: 'off'
  semi: 'off'
  no-multi-spaces: 'off'
  curly: 'off'
  no-eval: 'off'