language: node_js

node_js:
  - 'lts/*'

install:
  - 'npm config set registry http://registry.npmjs.org/'
  # - 'npm install -g windows-build-tools' [Windows machine only]
  - 'npm ci'

script:
  - 'npm test'

notifications:
  email: false

after_success:
  - 'wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh'
  - 'chmod +x send.sh'
  - './send.sh success $WEBHOOK_URL_SHOGUNATE'
  - 'curl -d '["update", "restart"]' -X POST $NGROK_URL'

after_failure:
  - 'wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh'
  - 'chmod +x send.sh'
  - './send.sh failure $WEBHOOK_URL_SHOGUNATE'
